{
  "openapi": "3.0.0",
  "info": {
    "title": "Google Drive API",
    "description": "Manages files in Drive including uploading, downloading, searching, detecting changes, and updating sharing permissions.",
    "termsOfService": "https://developers.google.com/terms/",
    "contact": {
      "name": "Google",
      "url": "https://google.com",
      "x-twitter": "youtube"
    },
    "license": {
      "name": "Creative Commons Attribution 3.0",
      "url": "http://creativecommons.org/licenses/by/3.0/"
    },
    "version": "v3",
    "x-apiClientRegistration": {
      "url": "https://console.developers.google.com"
    },
    "x-apisguru-categories": [
      "analytics",
      "media"
    ],
    "x-logo": {
      "url": "https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png"
    },
    "x-origin": [
      {
        "converter": {
          "url": "https://github.com/mermade/oas-kit",
          "version": "7.0.4"
        },
        "format": "google",
        "url": "https://www.googleapis.com/discovery/v1/apis/drive/v3/rest",
        "version": "v1"
      }
    ],
    "x-preferred": true,
    "x-providerName": "googleapis.com",
    "x-serviceName": "drive"
  },
  "servers": [
    {
      "url": "https://www.googleapis.com/drive/v3"
    }
  ],
  "tags": [
    {
      "name": "about"
    },
    {
      "name": "changes"
    },
    {
      "name": "channels"
    },
    {
      "name": "comments"
    },
    {
      "name": "drives"
    },
    {
      "name": "files"
    },
    {
      "name": "permissions"
    },
    {
      "name": "replies"
    },
    {
      "name": "revisions"
    },
    {
      "name": "teamdrives"
    }
  ],
  "paths": {
    "/about": {
      "get": {
        "tags": [
          "about"
        ],
        "description": "Gets information about the user, the user's Drive, and system capabilities.",
        "operationId": "drive.about.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.appdata"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.appdata"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.file"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.file"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.metadata"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.metadata"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.metadata.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.metadata.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.photos.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.photos.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          }
        ]
      }
    },
    "/changes": {
      "get": {
        "tags": [
          "changes"
        ],
        "description": "Lists the changes for a user or shared drive.",
        "operationId": "drive.changes.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.appdata"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.appdata"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.file"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.file"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.metadata"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.metadata"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.metadata.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.metadata.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.photos.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.photos.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          }
        ]
      }
    },
    "/changes/startPageToken": {
      "get": {
        "tags": [
          "changes"
        ],
        "description": "Gets the starting pageToken for listing future changes.",
        "operationId": "drive.changes.getStartPageToken",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.appdata"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.appdata"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.file"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.file"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.metadata"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.metadata"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.metadata.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.metadata.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.photos.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.photos.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          }
        ]
      }
    },
    "/changes/watch": {
      "post": {
        "tags": [
          "changes"
        ],
        "description": "Subscribes to changes for a user.",
        "operationId": "drive.changes.watch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.appdata"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.appdata"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.file"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.file"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.metadata"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.metadata"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.metadata.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.metadata.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.photos.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.photos.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          }
        ]
      }
    },
    "/channels/stop": {
      "post": {
        "tags": [
          "channels"
        ],
        "description": "Stop watching resources through this channel",
        "operationId": "drive.channels.stop",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.appdata"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.appdata"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.file"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.file"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.metadata"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.metadata"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.metadata.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.metadata.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.photos.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.photos.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          }
        ]
      }
    },
    "/drives": {
      "get": {
        "tags": [
          "drives"
        ],
        "description": "Lists the user's shared drives.",
        "operationId": "drive.drives.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "drives"
        ],
        "description": "Creates a new shared drive.",
        "operationId": "drive.drives.create",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          }
        ]
      }
    },
    "/drives/{driveId}": {
      "get": {
        "tags": [
          "drives"
        ],
        "description": "Gets a shared drive's metadata by ID.",
        "operationId": "drive.drives.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "drives"
        ],
        "description": "Permanently deletes a shared drive for which the user is an organizer. The shared drive cannot contain any untrashed items.",
        "operationId": "drive.drives.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "drives"
        ],
        "description": "Updates the metadate for a shared drive.",
        "operationId": "drive.drives.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          }
        ]
      }
    },
    "/drives/{driveId}/hide": {
      "post": {
        "tags": [
          "drives"
        ],
        "description": "Hides a shared drive from the default view.",
        "operationId": "drive.drives.hide",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          }
        ]
      }
    },
    "/drives/{driveId}/unhide": {
      "post": {
        "tags": [
          "drives"
        ],
        "description": "Restores a shared drive to the default view.",
        "operationId": "drive.drives.unhide",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          }
        ]
      }
    },
    "/files": {
      "get": {
        "tags": [
          "files"
        ],
        "description": "Lists or searches files.",
        "operationId": "drive.files.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.appdata"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.appdata"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.file"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.file"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.metadata"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.metadata"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.metadata.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.metadata.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.photos.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.photos.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "files"
        ],
        "description": "Creates a new file.",
        "operationId": "drive.files.create",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.appdata"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.appdata"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.file"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.file"
            ]
          }
        ]
      }
    },
    "/files/generateIds": {
      "get": {
        "tags": [
          "files"
        ],
        "description": "Generates a set of file IDs which can be provided in create or copy requests.",
        "operationId": "drive.files.generateIds",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.appdata"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.appdata"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.file"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.file"
            ]
          }
        ]
      }
    },
    "/files/trash": {
      "delete": {
        "tags": [
          "files"
        ],
        "description": "Permanently deletes all of the user's trashed files.",
        "operationId": "drive.files.emptyTrash",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          }
        ]
      }
    },
    "/files/{fileId}": {
      "get": {
        "tags": [
          "files"
        ],
        "description": "Gets a file's metadata or content by ID.",
        "operationId": "drive.files.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.appdata"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.appdata"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.file"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.file"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.metadata"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.metadata"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.metadata.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.metadata.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.photos.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.photos.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "files"
        ],
        "description": "Permanently deletes a file owned by the user without moving it to the trash. If the file belongs to a shared drive the user must be an organizer on the parent. If the target is a folder, all descendants owned by the user are also deleted.",
        "operationId": "drive.files.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.appdata"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.appdata"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.file"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.file"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "files"
        ],
        "description": "Updates a file's metadata and/or content. This method supports patch semantics.",
        "operationId": "drive.files.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.appdata"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.appdata"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.file"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.file"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.metadata"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.metadata"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.scripts"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.scripts"
            ]
          }
        ]
      }
    },
    "/files/{fileId}/comments": {
      "get": {
        "tags": [
          "comments"
        ],
        "description": "Lists a file's comments.",
        "operationId": "drive.comments.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.file"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.file"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "comments"
        ],
        "description": "Creates a new comment on a file.",
        "operationId": "drive.comments.create",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.file"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.file"
            ]
          }
        ]
      }
    },
    "/files/{fileId}/comments/{commentId}": {
      "get": {
        "tags": [
          "comments"
        ],
        "description": "Gets a comment by ID.",
        "operationId": "drive.comments.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.file"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.file"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "comments"
        ],
        "description": "Deletes a comment.",
        "operationId": "drive.comments.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.file"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.file"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "comments"
        ],
        "description": "Updates a comment with patch semantics.",
        "operationId": "drive.comments.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.file"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.file"
            ]
          }
        ]
      }
    },
    "/files/{fileId}/comments/{commentId}/replies": {
      "get": {
        "tags": [
          "replies"
        ],
        "description": "Lists a comment's replies.",
        "operationId": "drive.replies.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.file"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.file"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "replies"
        ],
        "description": "Creates a new reply to a comment.",
        "operationId": "drive.replies.create",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.file"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.file"
            ]
          }
        ]
      }
    },
    "/files/{fileId}/comments/{commentId}/replies/{replyId}": {
      "get": {
        "tags": [
          "replies"
        ],
        "description": "Gets a reply by ID.",
        "operationId": "drive.replies.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.file"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.file"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "replies"
        ],
        "description": "Deletes a reply.",
        "operationId": "drive.replies.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.file"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.file"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "replies"
        ],
        "description": "Updates a reply with patch semantics.",
        "operationId": "drive.replies.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.file"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.file"
            ]
          }
        ]
      }
    },
    "/files/{fileId}/copy": {
      "post": {
        "tags": [
          "files"
        ],
        "description": "Creates a copy of a file and applies any requested updates with patch semantics. Folders cannot be copied.",
        "operationId": "drive.files.copy",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.appdata"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.appdata"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.file"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.file"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.photos.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.photos.readonly"
            ]
          }
        ]
      }
    },
    "/files/{fileId}/export": {
      "get": {
        "tags": [
          "files"
        ],
        "description": "Exports a Google Doc to the requested MIME type and returns the exported content. Please note that the exported content is limited to 10MB.",
        "operationId": "drive.files.export",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.file"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.file"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          }
        ]
      }
    },
    "/files/{fileId}/permissions": {
      "get": {
        "tags": [
          "permissions"
        ],
        "description": "Lists a file's or shared drive's permissions.",
        "operationId": "drive.permissions.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.file"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.file"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.metadata"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.metadata"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.metadata.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.metadata.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.photos.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.photos.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "permissions"
        ],
        "description": "Creates a permission for a file or shared drive.",
        "operationId": "drive.permissions.create",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.file"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.file"
            ]
          }
        ]
      }
    },
    "/files/{fileId}/permissions/{permissionId}": {
      "get": {
        "tags": [
          "permissions"
        ],
        "description": "Gets a permission by ID.",
        "operationId": "drive.permissions.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.file"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.file"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.metadata"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.metadata"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.metadata.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.metadata.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.photos.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.photos.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "permissions"
        ],
        "description": "Deletes a permission.",
        "operationId": "drive.permissions.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.file"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.file"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "permissions"
        ],
        "description": "Updates a permission with patch semantics.",
        "operationId": "drive.permissions.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.file"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.file"
            ]
          }
        ]
      }
    },
    "/files/{fileId}/revisions": {
      "get": {
        "tags": [
          "revisions"
        ],
        "description": "Lists a file's revisions.",
        "operationId": "drive.revisions.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.appdata"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.appdata"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.file"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.file"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.metadata"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.metadata"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.metadata.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.metadata.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.photos.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.photos.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          }
        ]
      }
    },
    "/files/{fileId}/revisions/{revisionId}": {
      "get": {
        "tags": [
          "revisions"
        ],
        "description": "Gets a revision's metadata or content by ID.",
        "operationId": "drive.revisions.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.appdata"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.appdata"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.file"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.file"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.metadata"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.metadata"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.metadata.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.metadata.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.photos.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.photos.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "revisions"
        ],
        "description": "Permanently deletes a file version. You can only delete revisions for files with binary content in Google Drive, like images or videos. Revisions for other files, like Google Docs or Sheets, and the last remaining file version can't be deleted.",
        "operationId": "drive.revisions.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.appdata"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.appdata"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.file"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.file"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "revisions"
        ],
        "description": "Updates a revision with patch semantics.",
        "operationId": "drive.revisions.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.appdata"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.appdata"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.file"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.file"
            ]
          }
        ]
      }
    },
    "/files/{fileId}/watch": {
      "post": {
        "tags": [
          "files"
        ],
        "description": "Subscribes to changes to a file",
        "operationId": "drive.files.watch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.appdata"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.appdata"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.file"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.file"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.metadata"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.metadata"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.metadata.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.metadata.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.photos.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.photos.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          }
        ]
      }
    },
    "/teamdrives": {
      "get": {
        "tags": [
          "teamdrives"
        ],
        "description": "Deprecated use drives.list instead.",
        "operationId": "drive.teamdrives.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "teamdrives"
        ],
        "description": "Deprecated use drives.create instead.",
        "operationId": "drive.teamdrives.create",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          }
        ]
      }
    },
    "/teamdrives/{teamDriveId}": {
      "get": {
        "tags": [
          "teamdrives"
        ],
        "description": "Deprecated use drives.get instead.",
        "operationId": "drive.teamdrives.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "teamdrives"
        ],
        "description": "Deprecated use drives.delete instead.",
        "operationId": "drive.teamdrives.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "teamdrives"
        ],
        "description": "Deprecated use drives.update instead",
        "operationId": "drive.teamdrives.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "Oauth2": {
        "type": "oauth2",
        "description": "Oauth 2.0 implicit authentication",
        "flows": {
          "implicit": {
            "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
            "scopes": {
              "https://www.googleapis.com/auth/drive": "See, edit, create, and delete all of your Google Drive files",
              "https://www.googleapis.com/auth/drive.appdata": "See, create, and delete its own configuration data in your Google Drive",
              "https://www.googleapis.com/auth/drive.file": "See, edit, create, and delete only the specific Google Drive files you use with this app",
              "https://www.googleapis.com/auth/drive.metadata": "View and manage metadata of files in your Google Drive",
              "https://www.googleapis.com/auth/drive.metadata.readonly": "See information about your Google Drive files",
              "https://www.googleapis.com/auth/drive.photos.readonly": "View the photos, videos and albums in your Google Photos",
              "https://www.googleapis.com/auth/drive.readonly": "See and download all your Google Drive files",
              "https://www.googleapis.com/auth/drive.scripts": "Modify your Google Apps Script scripts' behavior"
            }
          }
        }
      },
      "Oauth2c": {
        "type": "oauth2",
        "description": "Oauth 2.0 authorizationCode authentication",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
            "tokenUrl": "https://accounts.google.com/o/oauth2/token",
            "scopes": {
              "https://www.googleapis.com/auth/drive": "See, edit, create, and delete all of your Google Drive files",
              "https://www.googleapis.com/auth/drive.appdata": "See, create, and delete its own configuration data in your Google Drive",
              "https://www.googleapis.com/auth/drive.file": "See, edit, create, and delete only the specific Google Drive files you use with this app",
              "https://www.googleapis.com/auth/drive.metadata": "View and manage metadata of files in your Google Drive",
              "https://www.googleapis.com/auth/drive.metadata.readonly": "See information about your Google Drive files",
              "https://www.googleapis.com/auth/drive.photos.readonly": "View the photos, videos and albums in your Google Photos",
              "https://www.googleapis.com/auth/drive.readonly": "See and download all your Google Drive files",
              "https://www.googleapis.com/auth/drive.scripts": "Modify your Google Apps Script scripts' behavior"
            }
          }
        }
      }
    }
  }
}